apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-green
  template:
    metadata:
      labels:
        app: app-green
    spec:
      containers:
      - name: app
        image: myacrdemo1.azurecr.io/demoapptesting:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-green-service
  namespace: green
spec:
  selector:
    app: app-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
